### ISSUE TITLE
Broken after recent update

### ISSUE THREAD

**Issue by rEnr3n** [rileyjshaw/dark-theme-everywhere#2]
Version: 4.0.6
Chromium 49.0.2623.110

I'm getting issues similar to user reviews in chrome web store page. The pages get dark effect even if I set it to default to Light with nothing on exceptions list. Changing the default to Dark doesn't change anything. Clicking the icon changes the page's color but refreshing it reverts it back. Also, I use Dark Reader with this one.

**Comment by rileyjshaw** [comment]
: ( sorry about that!! I'll look into it.

**Comment by MentalGear** [comment]
Same thing here, exceptions don't seem to be saved.

**Comment by rileyjshaw** [comment]
Hi @rhiv @MentalGear!

Thanks for the feedback. I just published a new version (v4.0.8), can you confirm if this is fixed once the update makes it to your browser? (It usually takes a few hours)

**Comment by rEnr3n** [comment]
Yup. Looks ok on me now. Is it intentional that pressing the button is just a temporary action? Pressing the button does its work but reloading the page will go back to its previous state. It's not saved in exception. Thanks.

**Comment by MentalGear** [comment]
Thanks for the update @rileyjshaw .
Yes, exceptions work now ! 👍 
But as @rhiv mentioned, pressing the button to switch theme of a webpage isn't saved - is this intended?

**Comment by rileyjshaw** [comment]
Yes, this is intentional - but adding the site to the blacklist is an
interesting idea!

I'm a bit concerned about how this would actually work in practice (do we
block the entire domain, for example, or just that specific page?)

A good compromise might be popping up a reminder link to the options page?
I'm hesitant to do that because I like that the extension doesn't throw
much text at users currently...

Do either of you have thoughts on how this might work?

**Comment by MentalGear** [comment]
Honestly, I think blocking the whole domain to the exception list would be the best idea because lets say you are on wired.com, switch theme for the current page to white, then you click any link on that page, you will be back with the black theme - which is very annoying to say the least.

I agree with you, best to keep it as light-weight UI-wise as possible ! :)

**Comment by rEnr3n** [comment]
I think subdomains would be better than just the domain. Sites like tumblr will be annoying to browse if you just add the whole domain to the list.

Most websites have similar color theme throughout their pages so per-page exclusion might be just too cumbersome.

**Comment by MentalGear** [comment]
Right, good thinking !
However there are also content creator sites that have their accounts as /subfolders.
A more in-depth solution that would cover those too would be to "somehow" check if the stylesheets on the current page match with the ones that had been initially switched to dark by the user for that domain.

That's quite elaborate to code though, so I guess subdomains should be alright for now.

**Comment by rileyjshaw** [comment]
> which is very annoying to say the least

Agreed!

> subdomains would be better than just the domain

Agreed!

> Most websites have similar color theme throughout their pages so per-page exclusion might be just too cumbersome

Agreed!

> However there are also content creator sites that have their accounts as /subfolders

As you mentioned, the detection of this type of site vs. a more uniform site would be very involved. I'd rather stick to simple & durable solutions; [Dark Reader](https://github.com/alexanderby/darkreader) has the custom route covered as far as I'm concerned.

> That's quite elaborate to code though, so I guess subdomains should be alright for now

Okay, I'll give it a shot! Closing this issue, since this discussion is unrelated.

**Comment by rileyjshaw** [comment]
@rhiv @MentalGear I just added persistent toggles in [v6.0.0](https://github.com/rileyjshaw/dark-theme-everywhere/commit/03e983b3d290f86483a2bc103ae2a2265f6a87b1).

I want to test it a bit before publishing to the Chrome store. Do you mind [testing the extension locally](https://developer.chrome.com/extensions/getstarted#unpacked) and getting back to me with feedback?

**Comment by rEnr3n** [comment]
I have set my default to dark. Clicking the button lightens the page and added to the list. But clicking it again darkens the page temporarily. The subdomain is not removed on the list. Refreshing the page gives a light page.

Similar thing happens even if I set default to light.

**Comment by rileyjshaw** [comment]
@rhiv yikes! Very silly mistake, should be fixed now. Let me know :)

**Comment by rEnr3n** [comment]
The pages don't immediately change when I change default from dark to light and vice versa. Refreshing the pages solves it. Other than that it's working great. Awesome! Thanks.

**Comment by rileyjshaw** [comment]
No problem!! Thanks for testing it out!! :)

**Comment by rileyjshaw** [comment]
Alright, I added a few tweaks and I'm pushing v6.0.0 the Chrome store!
(@rhiv @MentalGear, please rate & review the extension if you like it 👍)
