### ISSUE TITLE
A few other quirks

### ISSUE THREAD

**Issue by MentalGear** [rileyjshaw/dark-theme-everywhere#3]
- eradicates background images
  Probably to swap with black backgrounds, however on sites that use background images for container images (ex: change.org), elements just disappear. A better way would be to only do this if the element is body, or just dim the background image with the Darkened Media css filters code
- "clicked links" are shown as golden
  It seems an unnecessarily prominent and dominant colors to highlight links that have already been explored by the user. A darker blue than the usual link color would make more sense.
- text-selection highlight is red with font changing to blue
  This as well seems a rather peculiar choice

**Comment by MentalGear** [comment]
- button backgrounds disappear
  example: here on github button backgrounds are replaced by transparency.
  Is this intended behaviour ?

**Comment by rileyjshaw** [comment]
Hi @MentalGear! Thanks for logging all of these suggestions.

I agree that the color scheme could be refined. This one is based entirely off of Nicer Inverter's scheme. If you have the time, could you post an improved color scheme in #7?

"Eradicates background images" is a known issue, and my least favorite part of this extension. Since you've logged it separately in #6, I'm going to close this issue for now.
